language: python
python:
- '2.7'

install:
 - pip install pytest
 - python setup.py install

script:
 # Run integration tests locally since they require a Cortical.io API key
 - cd tests/unit/
 - py.test --cov ../../cortipy .

after_success:
 - pip install python-coveralls
 - coveralls
